# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title: 'jaeseokk.log'
tagline: ''
description: ''
url: 'https://jaeseook.github.io/'
baseurl: '/'

author:
  name: 'jaeseokk'

paginate: 5

gems:
    [jekyll-paginate, jekyll-gist]

vervose: true